version: '3'

services:
    elm:
        # Open a shell environment
        tty: true
        # Keeps the standard input open for sending over commands afterwards
        stdin_open: true
        # Nicer name for the container
        container_name: elm
        # Use the following image for this container
        build: docker/elm
        # Volumes mapped to the container
        volumes:
            - .:/home/elm/src
        # Ports forwarded to the container
        ports:
            - 8000:8000
            - 35729:35729
